# Generated by Django 3.1.7 on 2021-03-29 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleDetails', '0002_remove_mainmodules_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainmodules',
            name='status',
        ),
        migrations.RemoveField(
            model_name='submodules',
            name='sub_module_status',
        ),
    ]
