# Generated by Django 3.1.7 on 2021-03-29 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleDetails', '0003_auto_20210329_1505'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='submodules',
            table='sub_module',
        ),
    ]
